# Generated by Django 3.2.4 on 2023-05-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('Outlet_Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='designtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('I', 'Inactive'), ('A', 'Active')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='jobfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('I', 'Inactive'), ('A', 'Active')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='jobtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('I', 'Inactive'), ('A', 'Active')], max_length=255)),
                ('jobfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobfor')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('priority', models.CharField(choices=[('M', 'Medium'), ('T', 'TOP'), ('U', 'Urgent')], max_length=255)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('F', 'Follow Up'), ('C', 'Completed')], max_length=255)),
                ('dead_Line', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('designtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.designtype')),
                ('jobfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobfor')),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobtype')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Outlet_Management.showroom_mgmt')),
            ],
        ),
        migrations.AddField(
            model_name='designtype',
            name='jobfor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobfor'),
        ),
        migrations.AddField(
            model_name='designtype',
            name='jobtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobtype'),
        ),
    ]
