# Generated by Django 3.2.4 on 2023-05-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtype',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('Medium', 'Medium'), ('TOP', 'TOP'), ('Urgent', 'Urgent')], max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Follow Up', 'Follow Up'), ('Completed', 'Completed')], max_length=255),
        ),
        migrations.AlterField(
            model_name='jobfor',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
    ]
