# Generated by Django 3.2.4 on 2023-05-11 06:07

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand_mgmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='brandlocation_type_mgmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='brandtypes_mgmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='class_mgmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='light_type_mgmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='material_type_mgmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='showroom_mgmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rsm', models.CharField(blank=True, max_length=255, null=True)),
                ('asm', models.CharField(blank=True, max_length=255, null=True)),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
                ('cug_no', models.CharField(blank=True, max_length=255, null=True)),
                ('landline', models.CharField(blank=True, max_length=255, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='status_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255)),
                ('visibility', multiselectfield.db.fields.MultiSelectField(choices=[('Vendor', 'Vendor'), ('Assets', 'Assets')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_mgmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255)),
                ('vendor_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='outlet_media_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('Width', models.CharField(blank=True, max_length=255, null=True)),
                ('Height', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_image', models.ImageField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255)),
                ('other_Comments', models.TextField(blank=True, null=True)),
                ('branding_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandlocation_type_mgmt', to='Outlet_Management.brandlocation_type_mgmt')),
                ('branding_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandtypes_mgmt', to='Outlet_Management.brandtypes_mgmt')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_mgmt', to='Outlet_Management.class_mgmt')),
                ('light_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_type_mgmt', to='Outlet_Management.light_type_mgmt')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_type_mgmt', to='Outlet_Management.material_type_mgmt')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_mgmt', to='Outlet_Management.showroom_mgmt')),
            ],
        ),
        migrations.CreateModel(
            name='floor_mgnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('floor_image', models.ImageField(upload_to='uploads/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='Outlet_Management.showroom_mgmt')),
            ],
        ),
        migrations.CreateModel(
            name='degreeimage_mgnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('url', models.URLField()),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_image', to='Outlet_Management.showroom_mgmt')),
            ],
        ),
        migrations.CreateModel(
            name='add_advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('asset_image', models.ImageField(upload_to='uploads/')),
                ('model_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_on', models.DateField()),
                ('ad_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_management', to='Outlet_Management.status_management')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_mgmt', to='Outlet_Management.brand_mgmt')),
                ('outlet_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Outlet_Management.outlet_media_form')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_image', to='Outlet_Management.vendor_mgmt')),
            ],
        ),
    ]
