# Generated by Django 3.2.4 on 2023-05-11 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet_media_form',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_mgmt_add', to='Outlet_Management.brand_mgmt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outlet_media_form',
            name='model_product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brand_mgmt',
            name='status',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disabled', 'Disabled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='brandlocation_type_mgmt',
            name='status',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disabled', 'Disabled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='brandtypes_mgmt',
            name='status',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disabled', 'Disabled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='class_mgmt',
            name='status',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disabled', 'Disabled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='light_type_mgmt',
            name='status',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disabled', 'Disabled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='material_type_mgmt',
            name='status',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disabled', 'Disabled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='outlet_media_form',
            name='status',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disabled', 'Disabled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='status_management',
            name='status',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disabled', 'Disabled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor_mgmt',
            name='status',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disabled', 'Disabled')], max_length=255),
        ),
    ]
