# Generated by Django 3.2.4 on 2023-05-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outlet_Management', '0002_auto_20230511_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_mgmt',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
        migrations.AlterField(
            model_name='brandlocation_type_mgmt',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
        migrations.AlterField(
            model_name='brandtypes_mgmt',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
        migrations.AlterField(
            model_name='class_mgmt',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
        migrations.AlterField(
            model_name='light_type_mgmt',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
        migrations.AlterField(
            model_name='material_type_mgmt',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
        migrations.AlterField(
            model_name='status_management',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor_mgmt',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
    ]
