# Generated by Django 3.2.4 on 2023-05-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Outlet_Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('site_type', models.CharField(choices=[('R', 'Rent'), ('I', 'Own')], max_length=255)),
                ('site_location', models.CharField(blank=True, max_length=255, null=True)),
                ('branding_type', models.CharField(choices=[('O', 'Outdoor'), ('I', 'Mall')], max_length=255)),
                ('branding_location', models.CharField(blank=True, max_length=255, null=True)),
                ('Width', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('start_Date', models.DateField()),
                ('Rent', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_image', models.ImageField(upload_to='uploads/')),
                ('document', models.FileField(upload_to='Documents/')),
                ('status', models.CharField(choices=[('I', 'Inactive'), ('A', 'Active')], max_length=255)),
                ('other_comments', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Outlet_Management.material_type_mgmt')),
            ],
        ),
        migrations.CreateModel(
            name='add_advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_on', models.DateField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('status', models.TextField(choices=[('I', 'Inactive'), ('A', 'Active')], max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Outlet_Management.brandtypes_mgmt')),
                ('hoarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoarding.hoarding')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Outlet_Management.vendor_mgmt')),
            ],
        ),
    ]
