# Generated by Django 3.2.4 on 2023-05-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_advertisement',
            name='status',
            field=models.TextField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='branding_type',
            field=models.CharField(choices=[('Outdoor', 'Outdoor'), ('Mall', 'Mall')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='site_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Own', 'Own')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], max_length=255),
        ),
    ]
